site_name: SocialAll
repo_url: http://www.socialall.io/
repo_name: SocialAll
site_author: SandKlock
site_favicon: favicon32.png
pages:
- ['index.md', 'SocialAll']
- ['user-guide/facebook.md', 'User Guide', 'Facebook']
- ['user-guide/twitter.md', 'User Guide', 'Twitter']
- ['user-guide/linkedin.md', 'User Guide', 'Linkedin']
- ['user-guide/google.md', 'User Guide', 'Google Plus']
- ['user-guide/plurk.md', 'User Guide', 'Plurk']
- ['user-guide/tumblr.md', 'User Guide', 'Tumblr']
- ['user-guide/mailru.md', 'User Guide', 'Mail.Ru']
- ['user-guide/live.md', 'User Guide', 'Live']
- ['user-guide/reddit.md', 'User Guide', 'Reddit']
- ['user-guide/lastfm.md', 'User Guide', 'Last.fm']
- ['user-guide/vkontakte.md', 'User Guide', 'Vkontakte']
- ['user-guide/disqus.md', 'User Guide', 'Disqus']
- ['user-guide/wordpress.md', 'User Guide', 'Wordpress']
- ['user-guide/foursquare.md', 'User Guide', 'Foursquare']
- ['user-guide/github.md', 'User Guide', 'GitHub']
- ['user-guide/instagram.md', 'User Guide', 'Instagram']
- ['user-guide/pinterest.md', 'User Guide', 'Pinterest']
- ['user-guide/amazon.md', 'User Guide', 'Amazon']
- ['user-guide/ebay.md', 'User Guide', 'Ebay']
- ['developer-guide/index.md', 'Developer Guide', 'Getting Started']
- ['developer-guide/restful.md', 'Developer Guide', 'RESTful']
- ['developer-guide/nodejs.md', 'Developer Guide', 'Node.js']
- ['developer-guide/php.md', 'Developer Guide', 'PHP']
- ['developer-guide/user-object.md', 'Developer Guide', 'User Object']
theme: readthedocs
extra_css: ['css/soclall.css']
extra_javascript: ['js/soclall.js']
include_search: true
