site_name: SocialAll
site_url: https://socialall.dev/
repo_url: https://github.com/socialall-dev/socialall-docs-vi.git
repo_name: Github
site_author: SandKlock
site_favicon: favicon32.png
google_analytics: ['UA-143770830-1', 'socialall.dev']
nav:
- Home: 'index.md'
- User Guide:
  - 'Facebook': 'user-guide/facebook.md'
  - 'Twitter': 'user-guide/twitter.md'
  - 'Linkedin': 'user-guide/linkedin.md'
  - 'Google Plus': 'user-guide/google.md'
  - 'Plurk': 'user-guide/plurk.md'
  - 'Tumblr': 'user-guide/tumblr.md'
  - 'Mail.Ru': 'user-guide/mailru.md'
  - 'Live': 'user-guide/live.md'
  - 'Reddit': 'user-guide/reddit.md'
  - 'Last.fm': 'user-guide/lastfm.md'
  - 'Vkontakte': 'user-guide/vkontakte.md'
  - 'Disqus': 'user-guide/disqus.md'
  - 'Wordpress': 'user-guide/wordpress.md'
  - 'Foursquare': 'user-guide/foursquare.md'
  - 'GitHub': 'user-guide/github.md'
  - 'Instagram': 'user-guide/instagram.md'
  - 'Pinterest': 'user-guide/pinterest.md'
  - 'Amazon': 'user-guide/amazon.md'
  - 'Ebay': 'user-guide/ebay.md'
  - 'Yahoo': 'user-guide/yahoo.md'
  - 'Twitch': 'user-guide/twitch.md'
  - 'Steam': 'user-guide/steam.md'
- Developer Guide:
  - 'Getting Started': 'developer-guide/index.md'
  - 'RESTful': 'developer-guide/restful.md'
  - 'Node.js': 'developer-guide/nodejs.md'
  - 'PHP': 'developer-guide/php.md'
  - 'User Object': 'developer-guide/user-object.md'
  - 'Page Object': 'developer-guide/page-object.md'
theme: readthedocs
extra_css: 
  - css/soclall.css
extra_javascript: 
  - js/soclall.js
